### ISSUE TITLE
Implement text scanning and responses

### ISSUE THREAD

**Issue by Insprill** [Insprill/robot-insprill#2]
When a user sends a message, a link to a paste site, an image, or a file (under a certain size) it should be scanned and responded to if conditions are met.

Example configuration:
```yaml
auto-actions:
    # A list of channel IDs to scan, or `*` for any channel.
  - channels:
      - 1027121783792480296
    # What forms of media should be scanned?
    methods:
      - TEXT
      - BIN
      - IMAGE
      - FILE
    # Whether bot messages should be scanned.
    bots: false
    # A list of actions.
    actions:
        # A regex pattern to match against.
      - pattern: ".*failed to find 'plugin.yml'.*"
        # This should be able to reuse the custom commands response format.
        response:
          embeds:
            - title: "Your plugin.yml couldn't be found"
              description: |-
                Make sure it's in the correct location. If you are using Gradle or Maven it should be in the `src/main/resources` folder. 
                If you're not using those, it should be in the `src` folder, *not* a package.

   # Example to respond 'NO BIG BOY' whenever someone mentions it.
  - channels: *
    methods:
      - TEXT
    bots: false
    actions:
      - pattern: "(?i).*big ?boy.*"
        response:
          text: "NO BIG BOY"
```

Implementation notes:
- OCR can be done with [JavaCPP Presets for Tesseract](https://github.com/bytedeco/javacpp-presets/tree/master/tesseract). [Example project](https://github.com/piersy/BasicTesseractExampleGradle).
- Bin fetching can be done using the existing BinService enum and a little regex magic.
- Responses can use the `MessageBehavior#reply` function. This will make it clearer what the bot's responding to if an HTTP request or OCR scan takes a while.
- Response configs will use `BotConfig$Message`s.
- Files/bins over maybe a megabyte or two should be skipped since it would take ages to look through. Not sure of a good way to protect against images, maybe skip everything over x by y pixels?
