### ISSUE TITLE
Implement forms

### ISSUE THREAD

**Issue by Insprill** [Insprill/robot-insprill#3]
Forms would be channels that you need to fill out a form in order to post to.

Example configuration:
```yaml
forms:
  - channel: 000000000000000
    color: "#000000"
    completable: true
    fields:
      - name: Plugin Name
        type: TEXT
        min: 2
        max: 24
      - name: Plugin Description
        type: TEXT
      - name: Budget (USD)
        type: NUMBER
        min: 1
        max: 1000
      - name: Contact
        type: USER
```

Implementation notes:
- Once the user submits all required information, the bot will post it as an embed.
- There should be a button for OP to delete the post.
- The embed should have OP's tag as the author name, and OP's pfp as the author image.
- There should be a way to enter longer pieces of text than the user can post in one message.
- There should be an option to mark a post as completed.
- There should be the following types:
  - `TEXT`
    Takes a basic text input. Has two parameters, `min` and `max` defining the minimum and maximum length of the text.
  - `NUMBER`
    Takes a number as input. Has two parameters, `min` and `max` defining the minimum and maximum value of the number.
  - `USER`
    Takes a single mention of a user.
