### ISSUE TITLE
Implement restricted channels

### ISSUE THREAD

**Issue by Insprill** [Insprill/robot-insprill#4]
Restricted channels are channels that only allow certain types of media to be posted.

Example configuration:
```yaml
restricted-channels:
  - channel-id: 0000000000000000
    types:
      - IMAGE
      - VIDEO
      - LINK
      - COMMAND
    response:
      text: "This channel is only for images, videos, links, and commands!"
```

Implementation notes
- When a message is posted that doesn't include one of the provided types, the `response` message will be shown. This should either be only visible to the user or deleted after x seconds if that's not possible.
- Response configs will be `BotConfig$Message`s.
- `types` should be an enum. It could be implemented similarly to the `Statistic` enum, with each variant having a function that checks sent messages for the required media and returns whether it's valid.
