### ISSUE TITLE
Implement statistics channels

### ISSUE THREAD

**Issue by Insprill** [Insprill/robot-insprill#5]
Statistics channels are channels that display a certain statistic in the name.
These can be statistics about the server, like member counts, or from a social media platform like YouTube subscribers.

Example configuration:
```yaml
statistic-channels:
  - channel-id: 0000000000000000
    format: "CodedRed Subs: %s"
    statistic: YOUTUBE_SUBS
    data: UC_kPUW3XPrCCRT9a4Pnf1Tg
  - channel-id: 0000000000000000
    format: "CodedRed Views: %s"
    statistic: YOUTUBE_VIEWS
    data: UC_kPUW3XPrCCRT9a4Pnf1Tg
```

Implementation notes:
- The channel must already exist. It will not be created by the bot to simplify the implementation.
- The format field will define the channel name. It'll be formatted with a simple `String#format`, and `%s` being the value.
- The data field is a String that some statistics may use, like YOUTUBE_SUBS for the channel to get the sub count.
- The following statistics will exist:
  - `YOUTUBE_SUBS` - API key set via the `YOUTUBE_API_KEY` env var.
  - `YOUTUBE_VIEWS` - API key set via the `YOUTUBE_API_KEY` env var.
