### ISSUE TITLE
Implement a role selection command

### ISSUE THREAD

**Issue by Insprill** [Insprill/robot-insprill#6]
The role selector command is a command that will respond with an embed and a dropdown allowing users to pick what roles they want.

Example configuration:
```yaml
commands.slash.select-roles:
  - message:
      embed: ...
    roles:
      - id: 0000000000000000
        emoji: name:0000000000000000
```
This configuration may change based on the actual implementation. This should be taken more as a loose reference than a guide.

A similar example from the Modrinth Discord:
![Image](https://user-images.githubusercontent.com/52843537/216483606-8a8a6aef-fc55-4ff3-ba91-25434b861a39.png)
The main difference between ours and theirs is that theirs is a static message where you click a button that gives you the prompt. Ours would be a command to give the message & the prompt.

Implementation notes:
- The command name will be `select-roles`
- The `message` field will use `BotConfig$Message`.
- The response should be ephemeral.
