### ISSUE TITLE
Implement bot presence

### ISSUE THREAD

**Issue by Insprill** [Insprill/robot-insprill#7]
Add a config section containing different presences to cycle through.

Example configuration:
```yaml
presence:
  random: true
  interval: 3600
  presences:
    - type: PLAYING
      message: video games
      status: Online
    - type: WATCHING
      message: youtube
      status: dnd
```

Implementation notes:
- If `random` is true, a random presence will be picked, but not the one that was previously used.
- `interval` should be the time, in seconds, between presence updates.
- `presences` should be a List of `Presence`.
- `Presence` should be a new configuration section that holds an ActivityType, message, status, and optional URL.
